version: '3'

networks:
  routes:

services:
  mysql:
    image: mysql
    container_name: mysql_routes
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: routes
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - routes

  pma2:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: pma2_routes
    restart: unless-stopped
    ports:
      - '8888:80'
    environment:
      PMA_HOST: mysql
    networks:
      - routes