server:
  port: 4000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/routes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  main:
    allow-bean-definition-overriding: true
